# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  labelAnalysis: 'Hola'
  fecha: $(Date:yyyyMMdd)
  name: format('{0:yyyyMMdd}', pipeline.startTime)

steps:
- script: echo ${{ variables.labelAnalysis }}${{ variables.buildConfiguration }}${{ variables.name }}
  displayName: 'Imprimir variable'
