# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/PocRandD.Test/PocRandD.Test.csproj'

- script: dotnet build src/PocRandD/PocRandD.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration) output'

- task: DotNetCoreCLI@2 #https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '-o publishpath'
    zipAfterPublish: false
    modifyOutputPath: true

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
  

    
